### PR TITLE
feat: retry only on specific exit code

### PR DESCRIPTION
**Pull request by andersfischernielsen**
This will add support for retrying only on a specific error code. 

We use (and love) this action in Pleo, but have certain exit codes we'd like to retry for while for other exit codes we don't. 

This PR will add support for passing the `retry_on_exit_code` option to the action and only retry if the exit code is equal to the provided exit code to retry for (if I'm reading the logic correctly - let me know if that's not the case! 👍🏼).

### CODE REVIEW

**Comment by andersfischernielsen** [comment]
I apologize for all the auto-format changes - let me know if you'd like me to only change the `else if` and leave the formatting alone!

**Comment by nick-fields** [comment]
> I apologize for all the auto-format changes - let me know if you'd like me to only change the `else if` and leave the formatting alone!

Thanks for the contribution! I like the idea, just need to clean up the commit.

Could you undo the formatting changes? Adding a test would be nice too, see other ["tests"](https://github.com/nick-fields/retry/blob/master/.github/workflows/ci_cd.yml#L12) for examples of how I've been testing this.  One of these days I will add actual tests...

**Comment by andersfischernielsen** [comment]
Done and done 😄

**Comment by erwinw** [comment]
Hey @nick-fields , could this PR be merged in, please? 🙏🏻

**Comment by andersfischernielsen** [comment]
@nick-fields I'm unable to get the test workflow to run against this PR 🤔 I'm unsure if Actions are enabled for the repository since that'd prevent the workflow from running, but AFAICT it should be set up to run on all pushes (including this PR). Maybe I'm missing something obvious - I'd like to test it pre-merge 😄

**Comment by nick-fields** [comment]
Thanks for cleaning this up! Apologies for the delay, I was away for the holiday. I have actions disabled on contributions from forks for security reasons. I'll have to do some trickery to test it locally then I'll get this merged today.

**Comment by andersfischernielsen** [comment]
No worries - and amazing! 🙌🏼 Let me know if you see any unexpected behaviour 😄

**Comment by nick-fields** [comment]
Closing in favor of #58 which is your fork pulled into a branch on this repo so that Actions/tests run before merge.  See [comment](https://github.com/nick-fields/retry/pull/58#discussion_r853029068) regarding issue with implementation.

**Pull request closed without merging**
