### PR TITLE
Upgrade to Node 20

### PR DESCRIPTION
**Pull request by prichey**
_Replace the bullet points below with your answers_

### Description

Resolves https://github.com/nick-fields/retry/issues/125

More info here: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Without migrating from `@zeit/ncc` to `@vercel/ncc` I got the following, I think due to OpenSSL / Node version mismatch:

```
$ ncc build src/index.ts && husky install
ncc: Version 0.20.5
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at hashOf (evalmachine.<anonymous>:1:1478571)
    at module.exports (evalmachine.<anonymous>:1:1480625)
    at runCmd (evalmachine.<anonymous>:1:46940)
    at 819 (evalmachine.<anonymous>:1:43967)
    at __webpack_require__ (evalmachine.<anonymous>:1:216)
    at startup (evalmachine.<anonymous>:1:353)
    at module.exports.8 (evalmachine.<anonymous>:1:385)
    at evalmachine.<anonymous>:1:395 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

### Testing

- What tests were added?
  - n/a

### CODE REVIEW

**Comment by prichey** [comment]
@Jolg42 I'm not actually sure how to vet my changes here. The `ncc` build succeeded, but other than making sure the `test` script passes (it does), I'm unsure of the release process.

**Comment by Jolg42** [comment]
On your fork, I guess Actions are not enabled because there is no run here:
https://github.com/prichey/retry/actions
That would show if things are working as expected I think.

The easiest would be to have them running here for this PR, I think the GitHub Actions workflow  is waiting from the approval from a maintainer to run now.
Maybe @nick-fields could unblock that.

**Comment by prichey** [comment]
Actions are now enabled, and I have attempted to fix the `npm ci` issue by regenerating `package-lock.json`
Most recent run here: https://github.com/prichey/retry/actions/runs/7670357210

**Review by nick-fields — APPROVED** [review]
LGTM, thanks for the submission!

**Comment by nick-fields** [comment]
Tests passed, releasing now

**Pull request merged**
